dist: xenial

language: python

python:
  - "3.6"

before_script:
  - pip3 install -e .

script:
  - python3 -c "import power_planner"
  - python3 -m unittest discover -t . -p "test_*py" power_planner/utils

